// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ozcq8GxerrF1WYaqjsW34y
// Component: UjjZHnMR6P0wv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: bQMthM1hHKi7g/component
import Button from "../../Button"; // plasmic-import: thE0NQ9e6rBHAu/component
import ProductCard from "../../ProductCard"; // plasmic-import: Pn5M_QzIQn7ZB3/component
import Ratings from "../../Ratings"; // plasmic-import: 9S_qTaYwkjYj0t/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: 0qu_kH_ddiMZdR/component
import BlogPost from "../../BlogPost"; // plasmic-import: OzNhyBBwnUWeMi/component
import Footer from "../../Footer"; // plasmic-import: Ds72FX0K-kOF2Y/component
import ProductRow from "../../ProductRow"; // plasmic-import: keSq6YDh49oPso/component

import { useScreenVariants as useScreenVariantssOxgEMpX5WMfyx } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: sOxgEMpX5wMfyx/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_planty.module.css"; // plasmic-import: ozcq8GxerrF1WYaqjsW34y/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: UjjZHnMR6P0wv/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: ltwRL0I3A9Fa5u/icon
import ButtonArrowIcon from "./icons/PlasmicIcon__ButtonArrow"; // plasmic-import: RoL_y-hcNN8omK/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: N3zuMpArvgBzsN/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: le9jVYTVBu1qJc/icon
import QuotessvgIcon from "./icons/PlasmicIcon__Quotessvg"; // plasmic-import: Mr2BcpWHMWeOSR/icon

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  button?: p.Flex<typeof Button>;
  featureItem?: p.Flex<typeof FeatureItem>;
  bestSellers?: p.Flex<"div">;
  productRow?: p.Flex<typeof ProductRow>;
  bigPlants?: p.Flex<"div">;
  cactuses?: p.Flex<"div">;
  testimonials?: p.Flex<"div">;
};

export interface DefaultHomeProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantssOxgEMpX5WMfyx()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__dzrDh)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__qdPy)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__cNHfP)}>
                <Header
                  className={classNames("__wab_instance", sty.header__nP9O8)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___4DfA)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Real, beautiful plants \nright to your door"}
                  </h1>
                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__px9Dt
                      )}
                    >
                      {"See all plants"}
                    </div>
                    <ButtonArrowIcon
                      className={classNames(projectcss.all, sty.svg__gr6IR)}
                      role={"img"}
                    />
                  </Button>
                </p.Stack>
              </div>
            </p.Stack>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__x70S)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__nSVd1
                  )}
                >
                  {"Top Collections"}
                </h2>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__kRqY5)}
              >
                <div className={classNames(projectcss.all, sty.column__nU15V)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__d91Ad
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__sq00)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/galinaNMiziNqvJx5MUnsplashjpg.jpg",
                          fullWidth: 1920,
                          fullHeight: 1278,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$65.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__pttAz
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___73Vp)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__bHmFl
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__gHwLu)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/igorSonFvPxCqgtwcUnsplashjpg.jpg",
                          fullWidth: 640,
                          fullHeight: 481,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$80.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__p9OfV
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__pll22)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__sqcJg
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__kVypI)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/scottWebbORwRlTgBrPoUnsplashjpg.jpg",
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$40.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__c7AQg
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__r0G4Y)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__iedzp
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__coaGe)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg",
                          fullWidth: 640,
                          fullHeight: 427,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings___4COha
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <FeatureItem
                data-plasmic-name={"featureItem"}
                data-plasmic-override={overrides.featureItem}
                className={classNames("__wab_instance", sty.featureItem)}
              />
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__yuAmc)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uq1Y1
                  )}
                >
                  {"Featured Products"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__wmNn)}
              >
                <div className={classNames(projectcss.all, sty.column__cs1Fq)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__cyiNo
                    )}
                    price={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__owXN
                        )}
                      >
                        {"$160.00"}
                      </div>
                    }
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__nivF1
                        )}
                        numReviews={"(12 Review)"}
                        stars={"two" as const}
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r2TQ
                        )}
                      >
                        {"Designed Sofa"}
                      </div>
                    }
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__otAwr)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__gkWx
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___4Q9UH)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/f2.jpg",
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$200.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__iJOt
                        )}
                        stars={"four" as const}
                      />
                    }
                    title={"Dining Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__q7Tu6)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__j2Hlf
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__gQwzE)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/f3.jpg",
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__urgfM
                        )}
                        numReviews={"(23 Review)"}
                        stars={"five" as const}
                      />
                    }
                    title={"Chair and Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__do6Cp)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__fwf9C
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___0GGzv)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/f4.jpg",
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$299.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__e9Bok
                        )}
                        numReviews={"(35 Review)"}
                      />
                    }
                    title={"Modern Arm Chair"}
                    withReviews={true}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__ypOfa)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gblno
                  )}
                >
                  {"Latest Blog"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__zjKQ)}
              >
                <div className={classNames(projectcss.all, sty.column__sUhwe)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost___5KFko
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__uMjB)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/b1.jpg",
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__fMo6H)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__cnEkx
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__uxmgp)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/b2.jpg",
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__qpe6Z)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__ba0Tn
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__v0Hjp)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/planty/images/b3.jpg",
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__mNveD)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__wydeD)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"90px" as const}
                  src={{
                    src: "/plasmic/planty/images/adidas.png",
                    fullWidth: 90,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6Ol41)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"91px" as const}
                  src={{
                    src: "/plasmic/planty/images/hm.png",
                    fullWidth: 91,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hYtRw)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"98px" as const}
                  src={{
                    src: "/plasmic/planty/images/kappa.png",
                    fullWidth: 98,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__l6H51)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"124px" as const}
                  src={{
                    src: "/plasmic/planty/images/lacoste.png",
                    fullWidth: 124,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rLfHn)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"125px" as const}
                  src={{
                    src: "/plasmic/planty/images/levis.png",
                    fullWidth: 125,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            ) : null}
            {true ? (
              <Footer
                className={classNames("__wab_instance", sty.footer__dx9JS)}
              />
            ) : null}
          </div>
          <p.Stack
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ulZlF)}
              >
                <Icon2Icon
                  className={classNames(projectcss.all, sty.svg___6FSp0)}
                  role={"img"}
                />

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__uTz7
                  )}
                >
                  {"Best sellers"}
                </h2>
              </p.Stack>
            ) : null}
            {true ? (
              <ProductRow
                data-plasmic-name={"productRow"}
                data-plasmic-override={overrides.productRow}
                className={classNames("__wab_instance", sty.productRow)}
              />
            ) : null}
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___9OYzm)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__fc9Tt
                  )}
                >
                  {"Big plants"}
                </h2>
              </p.Stack>
            ) : null}
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__waMaC)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__d6AQb)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___9GK7K)}
                  displayHeight={
                    "270px /* plasmic-token: ObHWhBbrFxpNMB */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/planty/images/plant6Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__tgnGg)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__nk57)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__ijJdD)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__e5Vuk
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Donec finibus"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ebH1T
                    )}
                  >
                    {"bigplants"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__sAgUl
                    )}
                  >
                    {"$100.00"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__yRQol)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__jVy79)}
                  displayHeight={
                    "270px /* plasmic-token: ObHWhBbrFxpNMB */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/planty/images/plant1Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hotD5)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg___4WnxQ)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__kr42O)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___7CfJh
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Nulla suscipit"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g8C94
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___9MDrr
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___03Qi4)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__d4Tok)}
                  displayHeight={
                    "270px /* plasmic-token: ObHWhBbrFxpNMB */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/planty/images/plant7Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qWNn)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__eipM)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__ueNzP)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__n0RNi
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Sed consectetur"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ftWHh
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__lvM2
                    )}
                  >
                    {"$18.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__uYQzM)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rBpEw)}
                  displayHeight={
                    "270px /* plasmic-token: ObHWhBbrFxpNMB */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/planty/images/plant5Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lGvhx)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__o9Slm)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__boZw3)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__g5Nrh
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Vestibulum eget"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yftqr
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___3MadC
                    )}
                  >
                    {"$220.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__b8FNr)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__rqvBc
                  )}
                >
                  {"Cactuses"}
                </h2>
              </p.Stack>
            ) : null}
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__z1D17)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__o1G6C)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zxOEz)}
                  displayHeight={
                    "270px /* plasmic-token: ObHWhBbrFxpNMB */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/planty/images/plant41Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hJxr7)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__f3K5)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__o7Fdz)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__grP3B
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Cras molestie"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2Fe0U
                    )}
                  >
                    {"cactuses "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___1CBqL
                    )}
                  >
                    {"$24.99"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__u7XJd)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___0T66B)}
                  displayHeight={
                    "270px /* plasmic-token: ObHWhBbrFxpNMB */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/planty/images/plant31Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oiQIv)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__mSweP)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__iA)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__rRrEq
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Curabitur eu tempor"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eq8Uq
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___1Ulmq
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__cHjpP)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__qtlDt)}
                  displayHeight={
                    "270px /* plasmic-token: ObHWhBbrFxpNMB */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/planty/images/plant9Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__e3DBz)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__awBu7)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__xt9Xx)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__iHeN3
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Fusce sagittis"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xhXkX
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__wm54
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__cvCk0)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__c1Llc)}
                  displayHeight={
                    "270px /* plasmic-token: ObHWhBbrFxpNMB */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/planty/images/plant2Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__o48D)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg___5D3Xy)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__qxBIv)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___2UlDw
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Integer porta"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__csi6T
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___0A2Fv
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__tn9S0)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__v6Pxp
                  )}
                >
                  {"Testimonials"}
                </h2>
              </p.Stack>
            ) : null}
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__uGwGq)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__fFcL)}
              >
                <QuotessvgIcon
                  className={classNames(projectcss.all, sty.svg__zp7Gh)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__c2KD
                  )}
                >
                  {
                    "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                  }
                </div>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__oavxW)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__an13G
                      )}
                    >
                      {"JOHN DOPE,"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___2PlJj
                      )}
                    >
                      {" COLORADO, USA"}
                    </h5>
                  </p.Stack>
                ) : null}
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__o2Li)}
              >
                <QuotessvgIcon
                  className={classNames(projectcss.all, sty.svg___3U8QB)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xZDf
                  )}
                >
                  {
                    "Well I'll be d*mned. These plants really ARE greener than any of my recruits."
                  }
                </div>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__yj6Cp)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__sRwCt
                      )}
                    >
                      {"MAJOR PAYNE"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__sJnEz
                      )}
                    >
                      {", VA, USA"}
                    </h5>
                  </p.Stack>
                ) : null}
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <Footer className={classNames("__wab_instance", sty.footer__yduE1)} />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "h1",
    "button",
    "featureItem",
    "bestSellers",
    "productRow",
    "bigPlants",
    "cactuses",
    "testimonials"
  ],
  h1: ["h1"],
  button: ["button"],
  featureItem: ["featureItem"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  testimonials: ["testimonials"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  h1: "h1";
  button: typeof Button;
  featureItem: typeof FeatureItem;
  bestSellers: "div";
  productRow: typeof ProductRow;
  bigPlants: "div";
  cactuses: "div";
  testimonials: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHome__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    button: makeNodeComponent("button"),
    featureItem: makeNodeComponent("featureItem"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    testimonials: makeNodeComponent("testimonials"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
